modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
# updateJSONURL = "https://raw.githubusercontent.com/glektarssza/minecraft-create-goggles-curio/master/forge-update.json"
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
displayURL = "https://github.com/glektarssza/minecraft-player-handling-customizer"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''
